// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpQlUPmEXj4gJ5w-jIvHoLsOExJ81fQZ8',
    appId: '1:1017672470125:android:607b5431d7940cffe27964',
    messagingSenderId: '1017672470125',
    projectId: 'footbest-ba003',
    storageBucket: 'footbest-ba003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwPYxtuM2c1j5-Quw5XVIRktn_APkghN4',
    appId: '1:1017672470125:ios:5718ba6deded6cebe27964',
    messagingSenderId: '1017672470125',
    projectId: 'footbest-ba003',
    storageBucket: 'footbest-ba003.appspot.com',
    iosBundleId: 'com.example.footbest',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAsRlJD99KtsZNhUsnfmRaumHzvKR40vZk",
    authDomain: "footbest-ba003.firebaseapp.com",
    projectId: "footbest-ba003",
    storageBucket: "footbest-ba003.appspot.com",
    messagingSenderId: "1017672470125",
    appId: "1:1017672470125:web:4de03e887a8469c5e27964",
    measurementId: "G-BJFN0N6WP5"
  );
}
